product_type = 'connect_cloud'
'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json'
type = 'html'
entrypoint = 'essential_proteins_2.html'
source = 'essential_proteins_2.Rmd'
validate = true
files = [
  '/essential_proteins_2.html',
  '/essential_proteins_2_files',
  '/.posit/publish/Essential Proteins-GS51.toml',
  '/.posit/publish/deployments/deployment-CHKL.toml'
]
title = 'Essential Proteins'
